# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Георгий\Desktop\ФТИ\Восьмиполюсники и всё такое\design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1231, 783)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1200, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.optimization = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimization.sizePolicy().hasHeightForWidth())
        self.optimization.setSizePolicy(sizePolicy)
        self.optimization.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.optimization.setObjectName("optimization")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.optimization)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.optimization)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plot_opt_widget = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_opt_widget.sizePolicy().hasHeightForWidth())
        self.plot_opt_widget.setSizePolicy(sizePolicy)
        self.plot_opt_widget.setObjectName("plot_opt_widget")
        self.plot_opt_layout = QtWidgets.QVBoxLayout(self.plot_opt_widget)
        self.plot_opt_layout.setObjectName("plot_opt_layout")
        self.verticalLayout_2.addWidget(self.plot_opt_widget)
        self.widget_10 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_11 = QtWidgets.QWidget(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setMinimumSize(QtCore.QSize(600, 0))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.in_plot_repr = QtWidgets.QComboBox(self.widget_11)
        self.in_plot_repr.setObjectName("in_plot_repr")
        self.in_plot_repr.addItem("")
        self.in_plot_repr.addItem("")
        self.in_plot_repr.addItem("")
        self.horizontalLayout_5.addWidget(self.in_plot_repr)
        self.in_slider_Cz = QtWidgets.QSlider(self.widget_11)
        self.in_slider_Cz.setOrientation(QtCore.Qt.Horizontal)
        self.in_slider_Cz.setObjectName("in_slider_Cz")
        self.horizontalLayout_5.addWidget(self.in_slider_Cz)
        self.in_Cz = QtWidgets.QDoubleSpinBox(self.widget_11)
        self.in_Cz.setObjectName("in_Cz")
        self.horizontalLayout_5.addWidget(self.in_Cz)
        self.verticalLayout_4.addWidget(self.widget_11, 0, QtCore.Qt.AlignHCenter)
        self.widget_12 = QtWidgets.QWidget(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setMaximumSize(QtCore.QSize(800, 16777215))
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.check_contour = QtWidgets.QCheckBox(self.widget_12)
        self.check_contour.setObjectName("check_contour")
        self.horizontalLayout_8.addWidget(self.check_contour)
        self.check_autoscale = QtWidgets.QCheckBox(self.widget_12)
        self.check_autoscale.setObjectName("check_autoscale")
        self.horizontalLayout_8.addWidget(self.check_autoscale)
        self.verticalLayout_4.addWidget(self.widget_12, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.widget_10)
        self.gridLayout_2.addWidget(self.widget_3, 2, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.optimization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(500, 500))
        self.widget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_17 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_4.setObjectName("widget_4")
        self.formLayout = QtWidgets.QFormLayout(self.widget_4)
        self.formLayout.setObjectName("formLayout")
        self.widget_13 = QtWidgets.QWidget(self.widget_4)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_8 = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMinimumSize(QtCore.QSize(200, 50))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.in_S11_min = QtWidgets.QLineEdit(self.widget_8)
        self.in_S11_min.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_S11_min.setObjectName("in_S11_min")
        self.horizontalLayout_6.addWidget(self.in_S11_min, 0, QtCore.Qt.AlignLeft)
        self.label_21 = QtWidgets.QLabel(self.widget_8)
        self.label_21.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(47, 0))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_6.addWidget(self.label_21)
        self.verticalLayout_3.addWidget(self.widget_8)
        self.widget_14 = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setMinimumSize(QtCore.QSize(200, 50))
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_19 = QtWidgets.QLabel(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_11.addWidget(self.label_19)
        self.in_Z = QtWidgets.QLineEdit(self.widget_14)
        self.in_Z.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_Z.setObjectName("in_Z")
        self.horizontalLayout_11.addWidget(self.in_Z, 0, QtCore.Qt.AlignRight)
        self.label_29 = QtWidgets.QLabel(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_11.addWidget(self.label_29)
        self.verticalLayout_3.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setMinimumSize(QtCore.QSize(200, 50))
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_30 = QtWidgets.QLabel(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_12.addWidget(self.label_30)
        self.in_Z0 = QtWidgets.QLineEdit(self.widget_15)
        self.in_Z0.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_Z0.setObjectName("in_Z0")
        self.horizontalLayout_12.addWidget(self.in_Z0, 0, QtCore.Qt.AlignRight)
        self.label_31 = QtWidgets.QLabel(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_12.addWidget(self.label_31)
        self.verticalLayout_3.addWidget(self.widget_15)
        self.widget_9 = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QtCore.QSize(200, 50))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_22 = QtWidgets.QLabel(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_7.addWidget(self.label_22)
        self.in_epsilon = QtWidgets.QLineEdit(self.widget_9)
        self.in_epsilon.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_epsilon.setObjectName("in_epsilon")
        self.horizontalLayout_7.addWidget(self.in_epsilon, 0, QtCore.Qt.AlignRight)
        self.label_26 = QtWidgets.QLabel(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(47, 0))
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_7.addWidget(self.label_26)
        self.verticalLayout_3.addWidget(self.widget_9)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.widget_13)
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(200, 100))
        self.widget_7.setObjectName("widget_7")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout.setObjectName("gridLayout")
        self.label_23 = QtWidgets.QLabel(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 1, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 2, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 3, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.in_theta_min = QtWidgets.QLineEdit(self.widget_7)
        self.in_theta_min.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_theta_min.setObjectName("in_theta_min")
        self.gridLayout.addWidget(self.in_theta_min, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 30))
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.in_theta_step = QtWidgets.QLineEdit(self.widget_7)
        self.in_theta_step.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_theta_step.setObjectName("in_theta_step")
        self.gridLayout.addWidget(self.in_theta_step, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 1, 0, 1, 1)
        self.in_theta_max = QtWidgets.QLineEdit(self.widget_7)
        self.in_theta_max.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_theta_max.setObjectName("in_theta_max")
        self.gridLayout.addWidget(self.in_theta_max, 2, 1, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.widget_7)
        self.verticalLayout.addWidget(self.widget_4)
        self.label_16 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(400, 50))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.in_Ca_min = QtWidgets.QLineEdit(self.widget_2)
        self.in_Ca_min.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_Ca_min.setObjectName("in_Ca_min")
        self.horizontalLayout.addWidget(self.in_Ca_min)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.in_Ca_max = QtWidgets.QLineEdit(self.widget_2)
        self.in_Ca_max.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_Ca_max.setObjectName("in_Ca_max")
        self.horizontalLayout.addWidget(self.in_Ca_max)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.in_Ca_num = QtWidgets.QLineEdit(self.widget_2)
        self.in_Ca_num.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_Ca_num.setObjectName("in_Ca_num")
        self.horizontalLayout.addWidget(self.in_Ca_num)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(400, 50))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.in_Cb_min = QtWidgets.QLineEdit(self.widget_5)
        self.in_Cb_min.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_Cb_min.setObjectName("in_Cb_min")
        self.horizontalLayout_2.addWidget(self.in_Cb_min)
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.in_Cb_max = QtWidgets.QLineEdit(self.widget_5)
        self.in_Cb_max.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_Cb_max.setObjectName("in_Cb_max")
        self.horizontalLayout_2.addWidget(self.in_Cb_max)
        self.label_6 = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.in_Cb_num = QtWidgets.QLineEdit(self.widget_5)
        self.in_Cb_num.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_Cb_num.setObjectName("in_Cb_num")
        self.horizontalLayout_2.addWidget(self.in_Cb_num)
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(400, 50))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.in_Cab_min = QtWidgets.QLineEdit(self.widget_6)
        self.in_Cab_min.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_Cab_min.setObjectName("in_Cab_min")
        self.horizontalLayout_4.addWidget(self.in_Cab_min)
        self.label_11 = QtWidgets.QLabel(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.in_Cab_max = QtWidgets.QLineEdit(self.widget_6)
        self.in_Cab_max.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_Cab_max.setObjectName("in_Cab_max")
        self.horizontalLayout_4.addWidget(self.in_Cab_max)
        self.label_12 = QtWidgets.QLabel(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.in_Cab_num = QtWidgets.QLineEdit(self.widget_6)
        self.in_Cab_num.setMaximumSize(QtCore.QSize(50, 16777215))
        self.in_Cab_num.setObjectName("in_Cab_num")
        self.horizontalLayout_4.addWidget(self.in_Cab_num)
        self.verticalLayout.addWidget(self.widget_6)
        self.btn_compute = QtWidgets.QPushButton(self.widget)
        self.btn_compute.setObjectName("btn_compute")
        self.verticalLayout.addWidget(self.btn_compute)
        self.widget_16 = QtWidgets.QWidget(self.widget)
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_16)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_save_opt = QtWidgets.QPushButton(self.widget_16)
        self.btn_save_opt.setObjectName("btn_save_opt")
        self.gridLayout_3.addWidget(self.btn_save_opt, 0, 1, 1, 1)
        self.btn_open_opt = QtWidgets.QPushButton(self.widget_16)
        self.btn_open_opt.setObjectName("btn_open_opt")
        self.gridLayout_3.addWidget(self.btn_open_opt, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_16)
        self.gridLayout_2.addWidget(self.widget, 2, 0, 1, 1)
        self.tabWidget.addTab(self.optimization, "")
        self.afc = QtWidgets.QWidget()
        self.afc.setObjectName("afc")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.afc)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plot_afc_widget = QtWidgets.QWidget(self.afc)
        self.plot_afc_widget.setObjectName("plot_afc_widget")
        self.plot_afc_layout = QtWidgets.QVBoxLayout(self.plot_afc_widget)
        self.plot_afc_layout.setObjectName("plot_afc_layout")
        self.verticalLayout_5.addWidget(self.plot_afc_widget)
        self.widget_22 = QtWidgets.QWidget(self.afc)
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.widget_17 = QtWidgets.QWidget(self.widget_22)
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.check_autoscale_afc = QtWidgets.QCheckBox(self.widget_17)
        self.check_autoscale_afc.setObjectName("check_autoscale_afc")
        self.verticalLayout_6.addWidget(self.check_autoscale_afc)
        self.widget_18 = QtWidgets.QWidget(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_27 = QtWidgets.QLabel(self.widget_18)
        self.label_27.setMinimumSize(QtCore.QSize(27, 0))
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_13.addWidget(self.label_27)
        self.in_slider_Ca_afc = QtWidgets.QSlider(self.widget_18)
        self.in_slider_Ca_afc.setMinimumSize(QtCore.QSize(400, 0))
        self.in_slider_Ca_afc.setOrientation(QtCore.Qt.Horizontal)
        self.in_slider_Ca_afc.setObjectName("in_slider_Ca_afc")
        self.horizontalLayout_13.addWidget(self.in_slider_Ca_afc)
        self.in_Ca_afc = QtWidgets.QDoubleSpinBox(self.widget_18)
        self.in_Ca_afc.setObjectName("in_Ca_afc")
        self.horizontalLayout_13.addWidget(self.in_Ca_afc)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.label_34 = QtWidgets.QLabel(self.widget_18)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_13.addWidget(self.label_34)
        self.in_Ca_min_afc = QtWidgets.QLineEdit(self.widget_18)
        self.in_Ca_min_afc.setMaximumSize(QtCore.QSize(51, 16777215))
        self.in_Ca_min_afc.setObjectName("in_Ca_min_afc")
        self.horizontalLayout_13.addWidget(self.in_Ca_min_afc)
        self.label_36 = QtWidgets.QLabel(self.widget_18)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_13.addWidget(self.label_36)
        self.label_35 = QtWidgets.QLabel(self.widget_18)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_13.addWidget(self.label_35)
        self.in_Ca_max_afc = QtWidgets.QLineEdit(self.widget_18)
        self.in_Ca_max_afc.setMaximumSize(QtCore.QSize(51, 16777215))
        self.in_Ca_max_afc.setObjectName("in_Ca_max_afc")
        self.horizontalLayout_13.addWidget(self.in_Ca_max_afc)
        self.label_37 = QtWidgets.QLabel(self.widget_18)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_13.addWidget(self.label_37)
        self.verticalLayout_6.addWidget(self.widget_18)
        self.widget_20 = QtWidgets.QWidget(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_33 = QtWidgets.QLabel(self.widget_20)
        self.label_33.setMinimumSize(QtCore.QSize(27, 0))
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_15.addWidget(self.label_33)
        self.in_slider_Cb_afc = QtWidgets.QSlider(self.widget_20)
        self.in_slider_Cb_afc.setMinimumSize(QtCore.QSize(400, 0))
        self.in_slider_Cb_afc.setOrientation(QtCore.Qt.Horizontal)
        self.in_slider_Cb_afc.setObjectName("in_slider_Cb_afc")
        self.horizontalLayout_15.addWidget(self.in_slider_Cb_afc)
        self.in_Cb_afc = QtWidgets.QDoubleSpinBox(self.widget_20)
        self.in_Cb_afc.setObjectName("in_Cb_afc")
        self.horizontalLayout_15.addWidget(self.in_Cb_afc)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.label_42 = QtWidgets.QLabel(self.widget_20)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_15.addWidget(self.label_42)
        self.in_Cb_min_afc = QtWidgets.QLineEdit(self.widget_20)
        self.in_Cb_min_afc.setMaximumSize(QtCore.QSize(51, 16777215))
        self.in_Cb_min_afc.setObjectName("in_Cb_min_afc")
        self.horizontalLayout_15.addWidget(self.in_Cb_min_afc)
        self.label_43 = QtWidgets.QLabel(self.widget_20)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_15.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.widget_20)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_15.addWidget(self.label_44)
        self.in_Cb_max_afc = QtWidgets.QLineEdit(self.widget_20)
        self.in_Cb_max_afc.setMaximumSize(QtCore.QSize(51, 16777215))
        self.in_Cb_max_afc.setObjectName("in_Cb_max_afc")
        self.horizontalLayout_15.addWidget(self.in_Cb_max_afc)
        self.label_45 = QtWidgets.QLabel(self.widget_20)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_15.addWidget(self.label_45)
        self.verticalLayout_6.addWidget(self.widget_20)
        self.widget_19 = QtWidgets.QWidget(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_19.sizePolicy().hasHeightForWidth())
        self.widget_19.setSizePolicy(sizePolicy)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_32 = QtWidgets.QLabel(self.widget_19)
        self.label_32.setMinimumSize(QtCore.QSize(27, 0))
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_14.addWidget(self.label_32)
        self.in_slider_Cab_afc = QtWidgets.QSlider(self.widget_19)
        self.in_slider_Cab_afc.setMinimumSize(QtCore.QSize(400, 0))
        self.in_slider_Cab_afc.setOrientation(QtCore.Qt.Horizontal)
        self.in_slider_Cab_afc.setObjectName("in_slider_Cab_afc")
        self.horizontalLayout_14.addWidget(self.in_slider_Cab_afc)
        self.in_Cab_afc = QtWidgets.QDoubleSpinBox(self.widget_19)
        self.in_Cab_afc.setObjectName("in_Cab_afc")
        self.horizontalLayout_14.addWidget(self.in_Cab_afc)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.label_38 = QtWidgets.QLabel(self.widget_19)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_14.addWidget(self.label_38)
        self.in_Cab_min_afc = QtWidgets.QLineEdit(self.widget_19)
        self.in_Cab_min_afc.setMaximumSize(QtCore.QSize(51, 16777215))
        self.in_Cab_min_afc.setObjectName("in_Cab_min_afc")
        self.horizontalLayout_14.addWidget(self.in_Cab_min_afc)
        self.label_39 = QtWidgets.QLabel(self.widget_19)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_14.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.widget_19)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_14.addWidget(self.label_40)
        self.in_Cab_max_afc = QtWidgets.QLineEdit(self.widget_19)
        self.in_Cab_max_afc.setMaximumSize(QtCore.QSize(51, 16777215))
        self.in_Cab_max_afc.setObjectName("in_Cab_max_afc")
        self.horizontalLayout_14.addWidget(self.in_Cab_max_afc)
        self.label_41 = QtWidgets.QLabel(self.widget_19)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_14.addWidget(self.label_41)
        self.verticalLayout_6.addWidget(self.widget_19)
        self.horizontalLayout_16.addWidget(self.widget_17)
        self.verticalLayout_5.addWidget(self.widget_22)
        self.tabWidget.addTab(self.afc, "")
        self.horizontalLayout_9.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1231, 31))
        self.menubar.setObjectName("menubar")
        self.menuExport_data = QtWidgets.QMenu(self.menubar)
        self.menuExport_data.setObjectName("menuExport_data")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport_AFC_plot_as_png = QtWidgets.QAction(MainWindow)
        self.actionExport_AFC_plot_as_png.setCheckable(False)
        self.actionExport_AFC_plot_as_png.setObjectName("actionExport_AFC_plot_as_png")
        self.menuExport_data.addAction(self.actionExport_AFC_plot_as_png)
        self.menubar.addAction(self.menuExport_data.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.in_plot_repr.setItemText(0, _translate("MainWindow", "C_a"))
        self.in_plot_repr.setItemText(1, _translate("MainWindow", "C_b"))
        self.in_plot_repr.setItemText(2, _translate("MainWindow", "C_ab"))
        self.check_contour.setText(_translate("MainWindow", "Aligned contourplot"))
        self.check_autoscale.setText(_translate("MainWindow", "Autoscale colorbar"))
        self.label_17.setText(_translate("MainWindow", "Options:"))
        self.label_18.setText(_translate("MainWindow", "|S11|_min"))
        self.label_21.setText(_translate("MainWindow", "[dB]"))
        self.label_19.setText(_translate("MainWindow", "Z"))
        self.label_29.setText(_translate("MainWindow", "[Ohm]"))
        self.label_30.setText(_translate("MainWindow", "Z_0"))
        self.label_31.setText(_translate("MainWindow", "[Ohm]"))
        self.label_22.setText(_translate("MainWindow", "epsilon"))
        self.label_23.setText(_translate("MainWindow", "[deg]"))
        self.label_24.setText(_translate("MainWindow", "[deg]"))
        self.label_25.setText(_translate("MainWindow", "[deg]"))
        self.label_15.setText(_translate("MainWindow", "step:"))
        self.label_13.setText(_translate("MainWindow", "El. length:"))
        self.label_14.setText(_translate("MainWindow", "max:"))
        self.label_20.setText(_translate("MainWindow", "min:"))
        self.label_16.setText(_translate("MainWindow", "Optimization range:"))
        self.label.setText(_translate("MainWindow", "C_a min:"))
        self.label_2.setText(_translate("MainWindow", "[pF] max:"))
        self.label_3.setText(_translate("MainWindow", "[pF] points:"))
        self.label_4.setText(_translate("MainWindow", "C_b min:"))
        self.label_5.setText(_translate("MainWindow", "[pF] max:"))
        self.label_6.setText(_translate("MainWindow", "[pF] points:"))
        self.label_10.setText(_translate("MainWindow", "Cab min:"))
        self.label_11.setText(_translate("MainWindow", "[pF] max:"))
        self.label_12.setText(_translate("MainWindow", "[pF] points:"))
        self.btn_compute.setText(_translate("MainWindow", "Compute"))
        self.btn_save_opt.setText(_translate("MainWindow", "Save"))
        self.btn_open_opt.setText(_translate("MainWindow", "Open"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optimization), _translate("MainWindow", "Optimization"))
        self.check_autoscale_afc.setText(_translate("MainWindow", "Autoscale"))
        self.label_27.setText(_translate("MainWindow", "Ca"))
        self.label_34.setText(_translate("MainWindow", "from:"))
        self.label_36.setText(_translate("MainWindow", "[pF]"))
        self.label_35.setText(_translate("MainWindow", "to:"))
        self.label_37.setText(_translate("MainWindow", "[pF]"))
        self.label_33.setText(_translate("MainWindow", "Cb"))
        self.label_42.setText(_translate("MainWindow", "from:"))
        self.label_43.setText(_translate("MainWindow", "[pF]"))
        self.label_44.setText(_translate("MainWindow", "to:"))
        self.label_45.setText(_translate("MainWindow", "[pF]"))
        self.label_32.setText(_translate("MainWindow", "Cab"))
        self.label_38.setText(_translate("MainWindow", "from:"))
        self.label_39.setText(_translate("MainWindow", "[pF]"))
        self.label_40.setText(_translate("MainWindow", "to:"))
        self.label_41.setText(_translate("MainWindow", "[pF]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.afc), _translate("MainWindow", "AFC"))
        self.menuExport_data.setTitle(_translate("MainWindow", "Export data"))
        self.actionExport_AFC_plot_as_png.setText(_translate("MainWindow", "Export AFC plot as png "))

